# Schema for the views plugin configuration.
views.filter.season_filter:
  type: views_filter
  label: 'Season filter'
  mapping:
    hemisphere:
      type: string
      label: 'Hemisphere'
    date_field:
      type: string
      label: 'Date field'
    value:
      type: views.filter_value.season_filter
      label: 'Value'

views.filter_value.season_filter:
  type: mapping
  label: 'Value'
  mapping:
    winter:
      type: string
      label: 'Winter'
    spring:
      type: string
      label: 'Spring'
    summer:
      type: string
      label: 'Summer'
    autumn:
      type: string
      label: 'Autumn'
